### ISSUE TITLE
Interoperability with storm version checks 

### ISSUE THREAD

**Issue by samuelhnrq** [runfalk/storm-legacy#1]
Hello, first, amazing work keeping this thing alive. Secondly I wanted to ask something small but rather polemic... I'm not sure where do you want to go with this fork, but if drop-in-replacement of the original storm, is of any priority this fork has a rather small but critical flaw, it's [missing two lines](http://bazaar.launchpad.net/~storm/storm/trunk/view/head:/storm/__init__.py#L31) in __init__.py 

``` python
version = "0.20.0.99"
version_info = tuple([int(x) for x in version.split(".")])
```

I know it's kinda of _binding_ to add them back... But without it a lot of libraries won't even pass version validation, even though the API is still the same.

**Comment by runfalk** [comment]
Glad to hear there are other users out there!

That's a good question. I don't remember why I deleted them in the first place. However, I think it may be the correct call. For most projects you can simply update your `setup.py`, but since I have removed a lot of functionality (see README for a list of what) storm-legacy isn't really a reliable drop in replacement. So testing is always required.

I'm a bit torn on what is the best way forward. If I advertise a version, which one do you think would be best?

I suppose [this](https://github.com/stoq/stoq/blob/125353515a653349281864d815669e9200d677f4/stoq/lib/dependencies.py#L299) is where you want to use it?

**Comment by samuelhnrq** [comment]
Well, as for which version, one minor higher than the last one ever released, seems like a sensible choice. I mean it's 0.x.x anything goes really.

Yes, that is exactly where I intended to use it. And by the way, I already tried doing that locally and everything I tried worked flawlessly, even though I didn't run the test suite or did any extensive testing.

But mostly out of curiosity, why did you remove these features? Too much of a hassle to port to python 3? Are they that relevant anyway? IMHO nothing a big (at least bigger than what it is) warning in README.md can't fix.

**Comment by runfalk** [comment]
I'll re-add it. Your point makes sense.

I removed features mostly because I didn't need them and they were complex to port. Another reason is that I don't really know how some features work, and therefore I didn't know how to test them.

I am open to re-adding some of them through PRs.
